import { prisma } from "../lib/prisma";

const seedBulkPost = async () => {
  try {
    await prisma.post.createMany({
      data: [
        {
          title: "Post 1",
          content: "Content 1",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["tech"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 2",
          content: "Content 2",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["news"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 3",
          content: "Content 3",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["tips"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 4",
          content: "Content 4",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: true,
          status: "PUBLISHED",
          tags: ["mobile"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 5",
          content: "Content 5",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["ai"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 6",
          content: "Content 6",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["web"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 7",
          content: "Content 7",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["design"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 8",
          content: "Content 8",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["react"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 9",
          content: "Content 9",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["node"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 10",
          content: "Content 10",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: true,
          status: "PUBLISHED",
          tags: ["javascript"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 11",
          content: "Content 11",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["css"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 12",
          content: "Content 12",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["html"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 13",
          content: "Content 13",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["backend"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 14",
          content: "Content 14",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["frontend"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 15",
          content: "Content 15",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["dev"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 16",
          content: "Content 16",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["cloud"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 17",
          content: "Content 17",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["aws"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 18",
          content: "Content 18",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["docker"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 19",
          content: "Content 19",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["kubernetes"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 20",
          content: "Content 20",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["database"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 21",
          content: "Content 21",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["postgres"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 22",
          content: "Content 22",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: true,
          status: "PUBLISHED",
          tags: ["prisma"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 23",
          content: "Content 23",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["sql"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 24",
          content: "Content 24",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["api"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 25",
          content: "Content 25",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["rest"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 26",
          content: "Content 26",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["graphql"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 27",
          content: "Content 27",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["auth"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 28",
          content: "Content 28",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["jwt"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 29",
          content: "Content 29",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["security"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 30",
          content: "Content 30",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["testing"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 31",
          content: "Content 31",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["jest"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 32",
          content: "Content 32",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["vitest"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 33",
          content: "Content 33",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["ci"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 34",
          content: "Content 34",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: true,
          status: "PUBLISHED",
          tags: ["cd"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 35",
          content: "Content 35",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["devops"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 36",
          content: "Content 36",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["linux"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 37",
          content: "Content 37",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["bash"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 38",
          content: "Content 38",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["cli"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 39",
          content: "Content 39",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["performance"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 40",
          content: "Content 40",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["optimization"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 41",
          content: "Content 41",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["seo"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 42",
          content: "Content 42",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: true,
          status: "PUBLISHED",
          tags: ["marketing"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 43",
          content: "Content 43",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["analytics"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 44",
          content: "Content 44",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["startup"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 45",
          content: "Content 45",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["saas"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 46",
          content: "Content 46",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["product"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 47",
          content: "Content 47",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["ux"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 48",
          content: "Content 48",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "DRAFT",
          tags: ["ui"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },

        {
          title: "Post 49",
          content: "Content 49",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "PUBLISHED",
          tags: ["growth"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
        {
          title: "Post 50",
          content: "Content 50",
          thumbnail: "https://placehold.co/600x400",
          isFeatured: false,
          status: "ARCHIVED",
          tags: ["business"],
          authorId: "it8rWZmE0Pn00jtKkrKPxOUgpoQ7mK2E",
        },
      ],
    });
  } catch (error) {
    console.log(error);
  }
};

seedBulkPost();
